// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: workforce/leave/v1/leave_entitlement_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.workforce.leave.v1;

/**
 * Protobuf type {@code workforce.leave.v1.GetLeaveEntitlementResponse}
 */
public final class GetLeaveEntitlementResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:workforce.leave.v1.GetLeaveEntitlementResponse)
    GetLeaveEntitlementResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      GetLeaveEntitlementResponse.class.getName());
  }
  // Use GetLeaveEntitlementResponse.newBuilder() to construct.
  private GetLeaveEntitlementResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetLeaveEntitlementResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementServiceProto.internal_static_workforce_leave_v1_GetLeaveEntitlementResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementServiceProto.internal_static_workforce_leave_v1_GetLeaveEntitlementResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.class, com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.Builder.class);
  }

  private int bitField0_;
  public static final int LEAVE_ENTITLEMENT_FIELD_NUMBER = 1;
  private com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement leaveEntitlement_;
  /**
   * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
   * @return Whether the leaveEntitlement field is set.
   */
  @java.lang.Override
  public boolean hasLeaveEntitlement() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
   * @return The leaveEntitlement.
   */
  @java.lang.Override
  public com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement getLeaveEntitlement() {
    return leaveEntitlement_ == null ? com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.getDefaultInstance() : leaveEntitlement_;
  }
  /**
   * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementOrBuilder getLeaveEntitlementOrBuilder() {
    return leaveEntitlement_ == null ? com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.getDefaultInstance() : leaveEntitlement_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLeaveEntitlement());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeaveEntitlement());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse)) {
      return super.equals(obj);
    }
    com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse other = (com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse) obj;

    if (hasLeaveEntitlement() != other.hasLeaveEntitlement()) return false;
    if (hasLeaveEntitlement()) {
      if (!getLeaveEntitlement()
          .equals(other.getLeaveEntitlement())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeaveEntitlement()) {
      hash = (37 * hash) + LEAVE_ENTITLEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getLeaveEntitlement().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code workforce.leave.v1.GetLeaveEntitlementResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:workforce.leave.v1.GetLeaveEntitlementResponse)
      com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementServiceProto.internal_static_workforce_leave_v1_GetLeaveEntitlementResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementServiceProto.internal_static_workforce_leave_v1_GetLeaveEntitlementResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.class, com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.Builder.class);
    }

    // Construct using com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLeaveEntitlementFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leaveEntitlement_ = null;
      if (leaveEntitlementBuilder_ != null) {
        leaveEntitlementBuilder_.dispose();
        leaveEntitlementBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementServiceProto.internal_static_workforce_leave_v1_GetLeaveEntitlementResponse_descriptor;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse getDefaultInstanceForType() {
      return com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse build() {
      com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse buildPartial() {
      com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse result = new com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leaveEntitlement_ = leaveEntitlementBuilder_ == null
            ? leaveEntitlement_
            : leaveEntitlementBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse) {
        return mergeFrom((com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse other) {
      if (other == com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse.getDefaultInstance()) return this;
      if (other.hasLeaveEntitlement()) {
        mergeLeaveEntitlement(other.getLeaveEntitlement());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLeaveEntitlementFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement leaveEntitlement_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.Builder, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementOrBuilder> leaveEntitlementBuilder_;
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     * @return Whether the leaveEntitlement field is set.
     */
    public boolean hasLeaveEntitlement() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     * @return The leaveEntitlement.
     */
    public com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement getLeaveEntitlement() {
      if (leaveEntitlementBuilder_ == null) {
        return leaveEntitlement_ == null ? com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.getDefaultInstance() : leaveEntitlement_;
      } else {
        return leaveEntitlementBuilder_.getMessage();
      }
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public Builder setLeaveEntitlement(com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement value) {
      if (leaveEntitlementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leaveEntitlement_ = value;
      } else {
        leaveEntitlementBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public Builder setLeaveEntitlement(
        com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.Builder builderForValue) {
      if (leaveEntitlementBuilder_ == null) {
        leaveEntitlement_ = builderForValue.build();
      } else {
        leaveEntitlementBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public Builder mergeLeaveEntitlement(com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement value) {
      if (leaveEntitlementBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          leaveEntitlement_ != null &&
          leaveEntitlement_ != com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.getDefaultInstance()) {
          getLeaveEntitlementBuilder().mergeFrom(value);
        } else {
          leaveEntitlement_ = value;
        }
      } else {
        leaveEntitlementBuilder_.mergeFrom(value);
      }
      if (leaveEntitlement_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public Builder clearLeaveEntitlement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      leaveEntitlement_ = null;
      if (leaveEntitlementBuilder_ != null) {
        leaveEntitlementBuilder_.dispose();
        leaveEntitlementBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.Builder getLeaveEntitlementBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLeaveEntitlementFieldBuilder().getBuilder();
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    public com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementOrBuilder getLeaveEntitlementOrBuilder() {
      if (leaveEntitlementBuilder_ != null) {
        return leaveEntitlementBuilder_.getMessageOrBuilder();
      } else {
        return leaveEntitlement_ == null ?
            com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.getDefaultInstance() : leaveEntitlement_;
      }
    }
    /**
     * <code>.workforce.leave.v1.LeaveEntitlement leave_entitlement = 1 [json_name = "leaveEntitlement"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.Builder, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementOrBuilder> 
        getLeaveEntitlementFieldBuilder() {
      if (leaveEntitlementBuilder_ == null) {
        leaveEntitlementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlement.Builder, com.github.vnworkday.proto.workforce.leave.v1.LeaveEntitlementOrBuilder>(
                getLeaveEntitlement(),
                getParentForChildren(),
                isClean());
        leaveEntitlement_ = null;
      }
      return leaveEntitlementBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:workforce.leave.v1.GetLeaveEntitlementResponse)
  }

  // @@protoc_insertion_point(class_scope:workforce.leave.v1.GetLeaveEntitlementResponse)
  private static final com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse();
  }

  public static com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLeaveEntitlementResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLeaveEntitlementResponse>() {
    @java.lang.Override
    public GetLeaveEntitlementResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetLeaveEntitlementResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLeaveEntitlementResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.vnworkday.proto.workforce.leave.v1.GetLeaveEntitlementResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

