// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: workforce/leave/v1/leave_entitlement.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.workforce.leave.v1;

public final class LeaveEntitlementProto {
  private LeaveEntitlementProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      LeaveEntitlementProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workforce_leave_v1_LeaveEntitlement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_workforce_leave_v1_LeaveEntitlement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*workforce/leave/v1/leave_entitlement.p" +
      "roto\022\022workforce.leave.v1\"6\n\020LeaveEntitle" +
      "ment\022\016\n\002id\030\001 \001(\tR\002id\022\022\n\004name\030\002 \001(\tR\004name" +
      "B\260\001\n-com.github.vnworkday.proto.workforc" +
      "e.leave.v1B\025LeaveEntitlementProtoP\001\242\002\003WL" +
      "X\252\002\022Workforce.Leave.V1\312\002\022Workforce\\Leave" +
      "\\V1\342\002\036Workforce\\Leave\\V1\\GPBMetadata\352\002\024W" +
      "orkforce::Leave::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_workforce_leave_v1_LeaveEntitlement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_workforce_leave_v1_LeaveEntitlement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_workforce_leave_v1_LeaveEntitlement_descriptor,
        new java.lang.String[] { "Id", "Name", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
