// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

public interface ListTenantsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.tenant.v1.ListTenantsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  com.github.vnworkday.proto.shared.v1.Error getError();
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   */
  com.github.vnworkday.proto.shared.v1.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  com.github.vnworkday.proto.shared.v1.ResponsePagination getPagination();
  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   */
  com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder getPaginationOrBuilder();

  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant> 
      getTenantsList();
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  com.github.vnworkday.proto.account.tenant.v1.Tenant getTenants(int index);
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  int getTenantsCount();
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  java.util.List<? extends com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder> 
      getTenantsOrBuilderList();
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder getTenantsOrBuilder(
      int index);
}
