// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

/**
 * <pre>
 * Response for listing tenants.
 * </pre>
 *
 * Protobuf type {@code account.tenant.v1.ListTenantsResponse}
 */
public final class ListTenantsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:account.tenant.v1.ListTenantsResponse)
    ListTenantsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ListTenantsResponse.class.getName());
  }
  // Use ListTenantsResponse.newBuilder() to construct.
  private ListTenantsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListTenantsResponse() {
    tenants_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_ListTenantsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_ListTenantsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.class, com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ERROR_FIELD_NUMBER = 1;
  private com.github.vnworkday.proto.shared.v1.Error error_;
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.Error getError() {
    return error_ == null ? com.github.vnworkday.proto.shared.v1.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.github.vnworkday.proto.shared.v1.Error.getDefaultInstance() : error_;
  }

  public static final int PAGINATION_FIELD_NUMBER = 2;
  private com.github.vnworkday.proto.shared.v1.ResponsePagination pagination_;
  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.ResponsePagination getPagination() {
    return pagination_ == null ? com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance() : pagination_;
  }
  /**
   * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance() : pagination_;
  }

  public static final int TENANTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant> tenants_;
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  @java.lang.Override
  public java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant> getTenantsList() {
    return tenants_;
  }
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder> 
      getTenantsOrBuilderList() {
    return tenants_;
  }
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  @java.lang.Override
  public int getTenantsCount() {
    return tenants_.size();
  }
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.account.tenant.v1.Tenant getTenants(int index) {
    return tenants_.get(index);
  }
  /**
   * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder getTenantsOrBuilder(
      int index) {
    return tenants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getError());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPagination());
    }
    for (int i = 0; i < tenants_.size(); i++) {
      output.writeMessage(3, tenants_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPagination());
    }
    for (int i = 0; i < tenants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tenants_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse)) {
      return super.equals(obj);
    }
    com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse other = (com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse) obj;

    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!getTenantsList()
        .equals(other.getTenantsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    if (getTenantsCount() > 0) {
      hash = (37 * hash) + TENANTS_FIELD_NUMBER;
      hash = (53 * hash) + getTenantsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for listing tenants.
   * </pre>
   *
   * Protobuf type {@code account.tenant.v1.ListTenantsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.tenant.v1.ListTenantsResponse)
      com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_ListTenantsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_ListTenantsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.class, com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.Builder.class);
    }

    // Construct using com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getErrorFieldBuilder();
        getPaginationFieldBuilder();
        getTenantsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      if (tenantsBuilder_ == null) {
        tenants_ = java.util.Collections.emptyList();
      } else {
        tenants_ = null;
        tenantsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_ListTenantsResponse_descriptor;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse getDefaultInstanceForType() {
      return com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse build() {
      com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse buildPartial() {
      com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse result = new com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse result) {
      if (tenantsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          tenants_ = java.util.Collections.unmodifiableList(tenants_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tenants_ = tenants_;
      } else {
        result.tenants_ = tenantsBuilder_.build();
      }
    }

    private void buildPartial0(com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse) {
        return mergeFrom((com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse other) {
      if (other == com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      if (tenantsBuilder_ == null) {
        if (!other.tenants_.isEmpty()) {
          if (tenants_.isEmpty()) {
            tenants_ = other.tenants_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTenantsIsMutable();
            tenants_.addAll(other.tenants_);
          }
          onChanged();
        }
      } else {
        if (!other.tenants_.isEmpty()) {
          if (tenantsBuilder_.isEmpty()) {
            tenantsBuilder_.dispose();
            tenantsBuilder_ = null;
            tenants_ = other.tenants_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tenantsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTenantsFieldBuilder() : null;
          } else {
            tenantsBuilder_.addAllMessages(other.tenants_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.github.vnworkday.proto.account.tenant.v1.Tenant m =
                  input.readMessage(
                      com.github.vnworkday.proto.account.tenant.v1.Tenant.parser(),
                      extensionRegistry);
              if (tenantsBuilder_ == null) {
                ensureTenantsIsMutable();
                tenants_.add(m);
              } else {
                tenantsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.vnworkday.proto.shared.v1.Error error_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.Error, com.github.vnworkday.proto.shared.v1.Error.Builder, com.github.vnworkday.proto.shared.v1.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     * @return The error.
     */
    public com.github.vnworkday.proto.shared.v1.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.github.vnworkday.proto.shared.v1.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(com.github.vnworkday.proto.shared.v1.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(
        com.github.vnworkday.proto.shared.v1.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public Builder mergeError(com.github.vnworkday.proto.shared.v1.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          error_ != null &&
          error_ != com.github.vnworkday.proto.shared.v1.Error.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000001);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.github.vnworkday.proto.shared.v1.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.Error, com.github.vnworkday.proto.shared.v1.Error.Builder, com.github.vnworkday.proto.shared.v1.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.vnworkday.proto.shared.v1.Error, com.github.vnworkday.proto.shared.v1.Error.Builder, com.github.vnworkday.proto.shared.v1.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private com.github.vnworkday.proto.shared.v1.ResponsePagination pagination_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.ResponsePagination, com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder, com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder> paginationBuilder_;
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     * @return The pagination.
     */
    public com.github.vnworkday.proto.shared.v1.ResponsePagination getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder setPagination(com.github.vnworkday.proto.shared.v1.ResponsePagination value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder setPagination(
        com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder mergePagination(com.github.vnworkday.proto.shared.v1.ResponsePagination value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pagination_ != null &&
          pagination_ != com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      if (pagination_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <code>.shared.v1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.ResponsePagination, com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder, com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.vnworkday.proto.shared.v1.ResponsePagination, com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder, com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }

    private java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant> tenants_ =
      java.util.Collections.emptyList();
    private void ensureTenantsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        tenants_ = new java.util.ArrayList<com.github.vnworkday.proto.account.tenant.v1.Tenant>(tenants_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.vnworkday.proto.account.tenant.v1.Tenant, com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder, com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder> tenantsBuilder_;

    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant> getTenantsList() {
      if (tenantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tenants_);
      } else {
        return tenantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public int getTenantsCount() {
      if (tenantsBuilder_ == null) {
        return tenants_.size();
      } else {
        return tenantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public com.github.vnworkday.proto.account.tenant.v1.Tenant getTenants(int index) {
      if (tenantsBuilder_ == null) {
        return tenants_.get(index);
      } else {
        return tenantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder setTenants(
        int index, com.github.vnworkday.proto.account.tenant.v1.Tenant value) {
      if (tenantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantsIsMutable();
        tenants_.set(index, value);
        onChanged();
      } else {
        tenantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder setTenants(
        int index, com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder builderForValue) {
      if (tenantsBuilder_ == null) {
        ensureTenantsIsMutable();
        tenants_.set(index, builderForValue.build());
        onChanged();
      } else {
        tenantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder addTenants(com.github.vnworkday.proto.account.tenant.v1.Tenant value) {
      if (tenantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantsIsMutable();
        tenants_.add(value);
        onChanged();
      } else {
        tenantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder addTenants(
        int index, com.github.vnworkday.proto.account.tenant.v1.Tenant value) {
      if (tenantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantsIsMutable();
        tenants_.add(index, value);
        onChanged();
      } else {
        tenantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder addTenants(
        com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder builderForValue) {
      if (tenantsBuilder_ == null) {
        ensureTenantsIsMutable();
        tenants_.add(builderForValue.build());
        onChanged();
      } else {
        tenantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder addTenants(
        int index, com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder builderForValue) {
      if (tenantsBuilder_ == null) {
        ensureTenantsIsMutable();
        tenants_.add(index, builderForValue.build());
        onChanged();
      } else {
        tenantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder addAllTenants(
        java.lang.Iterable<? extends com.github.vnworkday.proto.account.tenant.v1.Tenant> values) {
      if (tenantsBuilder_ == null) {
        ensureTenantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tenants_);
        onChanged();
      } else {
        tenantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder clearTenants() {
      if (tenantsBuilder_ == null) {
        tenants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tenantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public Builder removeTenants(int index) {
      if (tenantsBuilder_ == null) {
        ensureTenantsIsMutable();
        tenants_.remove(index);
        onChanged();
      } else {
        tenantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder getTenantsBuilder(
        int index) {
      return getTenantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder getTenantsOrBuilder(
        int index) {
      if (tenantsBuilder_ == null) {
        return tenants_.get(index);  } else {
        return tenantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public java.util.List<? extends com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder> 
         getTenantsOrBuilderList() {
      if (tenantsBuilder_ != null) {
        return tenantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tenants_);
      }
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder addTenantsBuilder() {
      return getTenantsFieldBuilder().addBuilder(
          com.github.vnworkday.proto.account.tenant.v1.Tenant.getDefaultInstance());
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder addTenantsBuilder(
        int index) {
      return getTenantsFieldBuilder().addBuilder(
          index, com.github.vnworkday.proto.account.tenant.v1.Tenant.getDefaultInstance());
    }
    /**
     * <code>repeated .account.tenant.v1.Tenant tenants = 3 [json_name = "tenants"];</code>
     */
    public java.util.List<com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder> 
         getTenantsBuilderList() {
      return getTenantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.vnworkday.proto.account.tenant.v1.Tenant, com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder, com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder> 
        getTenantsFieldBuilder() {
      if (tenantsBuilder_ == null) {
        tenantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.vnworkday.proto.account.tenant.v1.Tenant, com.github.vnworkday.proto.account.tenant.v1.Tenant.Builder, com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder>(
                tenants_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        tenants_ = null;
      }
      return tenantsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:account.tenant.v1.ListTenantsResponse)
  }

  // @@protoc_insertion_point(class_scope:account.tenant.v1.ListTenantsResponse)
  private static final com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse();
  }

  public static com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTenantsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListTenantsResponse>() {
    @java.lang.Override
    public ListTenantsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTenantsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTenantsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.vnworkday.proto.account.tenant.v1.ListTenantsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

