// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

public final class TenantServiceProto {
  private TenantServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      TenantServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_CreateTenantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_CreateTenantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_CreateTenantResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_CreateTenantResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_GetTenantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_GetTenantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_GetTenantResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_GetTenantResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_ListTenantsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_ListTenantsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_ListTenantsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_ListTenantsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_UpdateTenantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_UpdateTenantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_UpdateTenantResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_UpdateTenantResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_DeleteTenantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_DeleteTenantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_tenant_v1_DeleteTenantResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_tenant_v1_DeleteTenantResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&account/tenant/v1/tenant_service.proto" +
      "\022\021account.tenant.v1\032\036account/tenant/v1/t" +
      "enant.proto\")\n\023CreateTenantRequest\022\022\n\004na" +
      "me\030\001 \001(\tR\004name\"I\n\024CreateTenantResponse\0221" +
      "\n\006tenant\030\001 \001(\0132\031.account.tenant.v1.Tenan" +
      "tR\006tenant\"\"\n\020GetTenantRequest\022\016\n\002id\030\001 \001(" +
      "\tR\002id\"F\n\021GetTenantResponse\0221\n\006tenant\030\001 \001" +
      "(\0132\031.account.tenant.v1.TenantR\006tenant\"f\n" +
      "\022ListTenantsRequest\022\033\n\tpage_size\030\001 \001(\005R\010" +
      "pageSize\022\035\n\npage_token\030\002 \001(\005R\tpageToken\022" +
      "\024\n\005query\030\003 \001(\tR\005query\"r\n\023ListTenantsResp" +
      "onse\0223\n\007tenants\030\001 \003(\0132\031.account.tenant.v" +
      "1.TenantR\007tenants\022&\n\017next_page_token\030\002 \001" +
      "(\tR\rnextPageToken\"9\n\023UpdateTenantRequest" +
      "\022\016\n\002id\030\001 \001(\tR\002id\022\022\n\004name\030\002 \001(\tR\004name\"I\n\024" +
      "UpdateTenantResponse\0221\n\006tenant\030\001 \001(\0132\031.a" +
      "ccount.tenant.v1.TenantR\006tenant\"%\n\023Delet" +
      "eTenantRequest\022\016\n\002id\030\001 \001(\tR\002id\"&\n\024Delete" +
      "TenantResponse\022\016\n\002id\030\001 \001(\tR\002id2\362\003\n\rTenan" +
      "tService\022a\n\014CreateTenant\022&.account.tenan" +
      "t.v1.CreateTenantRequest\032\'.account.tenan" +
      "t.v1.CreateTenantResponse\"\000\022X\n\tGetTenant" +
      "\022#.account.tenant.v1.GetTenantRequest\032$." +
      "account.tenant.v1.GetTenantResponse\"\000\022^\n" +
      "\013ListTenants\022%.account.tenant.v1.ListTen" +
      "antsRequest\032&.account.tenant.v1.ListTena" +
      "ntsResponse\"\000\022a\n\014UpdateTenant\022&.account." +
      "tenant.v1.UpdateTenantRequest\032\'.account." +
      "tenant.v1.UpdateTenantResponse\"\000\022a\n\014Dele" +
      "teTenant\022&.account.tenant.v1.DeleteTenan" +
      "tRequest\032\'.account.tenant.v1.DeleteTenan" +
      "tResponse\"\000B\250\001\n,com.github.vnworkday.pro" +
      "to.account.tenant.v1B\022TenantServiceProto" +
      "P\001\242\002\003ATX\252\002\021Account.Tenant.V1\312\002\021Account\\T" +
      "enant\\V1\342\002\035Account\\Tenant\\V1\\GPBMetadata" +
      "\352\002\023Account::Tenant::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.vnworkday.proto.account.tenant.v1.TenantProto.getDescriptor(),
        });
    internal_static_account_tenant_v1_CreateTenantRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_account_tenant_v1_CreateTenantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_CreateTenantRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_account_tenant_v1_CreateTenantResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_account_tenant_v1_CreateTenantResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_CreateTenantResponse_descriptor,
        new java.lang.String[] { "Tenant", });
    internal_static_account_tenant_v1_GetTenantRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_account_tenant_v1_GetTenantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_GetTenantRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_account_tenant_v1_GetTenantResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_account_tenant_v1_GetTenantResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_GetTenantResponse_descriptor,
        new java.lang.String[] { "Tenant", });
    internal_static_account_tenant_v1_ListTenantsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_account_tenant_v1_ListTenantsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_ListTenantsRequest_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", "Query", });
    internal_static_account_tenant_v1_ListTenantsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_account_tenant_v1_ListTenantsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_ListTenantsResponse_descriptor,
        new java.lang.String[] { "Tenants", "NextPageToken", });
    internal_static_account_tenant_v1_UpdateTenantRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_account_tenant_v1_UpdateTenantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_UpdateTenantRequest_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_account_tenant_v1_UpdateTenantResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_account_tenant_v1_UpdateTenantResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_UpdateTenantResponse_descriptor,
        new java.lang.String[] { "Tenant", });
    internal_static_account_tenant_v1_DeleteTenantRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_account_tenant_v1_DeleteTenantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_DeleteTenantRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_account_tenant_v1_DeleteTenantResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_account_tenant_v1_DeleteTenantResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_tenant_v1_DeleteTenantResponse_descriptor,
        new java.lang.String[] { "Id", });
    descriptor.resolveAllFeaturesImmutable();
    com.github.vnworkday.proto.account.tenant.v1.TenantProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
