// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

/**
 * Protobuf enum {@code account.tenant.v1.TenantSubscriptionType}
 */
public enum TenantSubscriptionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED = 0;</code>
   */
  TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Default. Basic subscription is a subscription that provides basic features with most affordable pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_BASIC = 1;</code>
   */
  TENANT_SUBSCRIPTION_TYPE_BASIC(1),
  /**
   * <pre>
   * Standard subscription is a subscription that provides standard features with advanced pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_STANDARD = 2;</code>
   */
  TENANT_SUBSCRIPTION_TYPE_STANDARD(2),
  /**
   * <pre>
   * Premium subscription is a subscription that provides premium features with the highest pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_PREMIUM = 3;</code>
   */
  TENANT_SUBSCRIPTION_TYPE_PREMIUM(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      TenantSubscriptionType.class.getName());
  }
  /**
   * <code>TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Default. Basic subscription is a subscription that provides basic features with most affordable pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_BASIC = 1;</code>
   */
  public static final int TENANT_SUBSCRIPTION_TYPE_BASIC_VALUE = 1;
  /**
   * <pre>
   * Standard subscription is a subscription that provides standard features with advanced pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_STANDARD = 2;</code>
   */
  public static final int TENANT_SUBSCRIPTION_TYPE_STANDARD_VALUE = 2;
  /**
   * <pre>
   * Premium subscription is a subscription that provides premium features with the highest pricing.
   * </pre>
   *
   * <code>TENANT_SUBSCRIPTION_TYPE_PREMIUM = 3;</code>
   */
  public static final int TENANT_SUBSCRIPTION_TYPE_PREMIUM_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TenantSubscriptionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TenantSubscriptionType forNumber(int value) {
    switch (value) {
      case 0: return TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED;
      case 1: return TENANT_SUBSCRIPTION_TYPE_BASIC;
      case 2: return TENANT_SUBSCRIPTION_TYPE_STANDARD;
      case 3: return TENANT_SUBSCRIPTION_TYPE_PREMIUM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TenantSubscriptionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TenantSubscriptionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TenantSubscriptionType>() {
          public TenantSubscriptionType findValueByNumber(int number) {
            return TenantSubscriptionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.vnworkday.proto.account.tenant.v1.TenantProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final TenantSubscriptionType[] VALUES = values();

  public static TenantSubscriptionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TenantSubscriptionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:account.tenant.v1.TenantSubscriptionType)
}

