// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

/**
 * <pre>
 * For updating a tenant.
 * </pre>
 *
 * Protobuf type {@code account.tenant.v1.UpdateTenantRequest}
 */
public final class UpdateTenantRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:account.tenant.v1.UpdateTenantRequest)
    UpdateTenantRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      UpdateTenantRequest.class.getName());
  }
  // Use UpdateTenantRequest.newBuilder() to construct.
  private UpdateTenantRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateTenantRequest() {
    id_ = "";
    name_ = "";
    subscriptionType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_UpdateTenantRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_UpdateTenantRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.class, com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.Builder.class);
  }

  private int bitField0_;
  public static final int INFO_FIELD_NUMBER = 1;
  private com.github.vnworkday.proto.shared.v1.RequestInfo info_;
  /**
   * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
   * @return Whether the info field is set.
   */
  @java.lang.Override
  public boolean hasInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
   * @return The info.
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.RequestInfo getInfo() {
    return info_ == null ? com.github.vnworkday.proto.shared.v1.RequestInfo.getDefaultInstance() : info_;
  }
  /**
   * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
   */
  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.RequestInfoOrBuilder getInfoOrBuilder() {
    return info_ == null ? com.github.vnworkday.proto.shared.v1.RequestInfo.getDefaultInstance() : info_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * Required. The ID of the tenant to update.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The ID of the tenant to update.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Required. The new name of the tenant. This must be unique across all tenants.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The new name of the tenant. This must be unique across all tenants.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBSCRIPTION_TYPE_FIELD_NUMBER = 4;
  private int subscriptionType_ = 0;
  /**
   * <pre>
   * Required. The new type of subscription for the tenant.
   * </pre>
   *
   * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
   * @return The enum numeric value on the wire for subscriptionType.
   */
  @java.lang.Override public int getSubscriptionTypeValue() {
    return subscriptionType_;
  }
  /**
   * <pre>
   * Required. The new type of subscription for the tenant.
   * </pre>
   *
   * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
   * @return The subscriptionType.
   */
  @java.lang.Override public com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType getSubscriptionType() {
    com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType result = com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.forNumber(subscriptionType_);
    return result == null ? com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.UNRECOGNIZED : result;
  }

  public static final int SELF_REGISTRATION_ENABLED_FIELD_NUMBER = 5;
  private boolean selfRegistrationEnabled_ = false;
  /**
   * <pre>
   * Optional. Whether self-registration is enabled for the tenant. Defaults to false if not set.
   * </pre>
   *
   * <code>bool self_registration_enabled = 5 [json_name = "selfRegistrationEnabled"];</code>
   * @return The selfRegistrationEnabled.
   */
  @java.lang.Override
  public boolean getSelfRegistrationEnabled() {
    return selfRegistrationEnabled_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    if (subscriptionType_ != com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, subscriptionType_);
    }
    if (selfRegistrationEnabled_ != false) {
      output.writeBool(5, selfRegistrationEnabled_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    if (subscriptionType_ != com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.TENANT_SUBSCRIPTION_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, subscriptionType_);
    }
    if (selfRegistrationEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, selfRegistrationEnabled_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest)) {
      return super.equals(obj);
    }
    com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest other = (com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest) obj;

    if (hasInfo() != other.hasInfo()) return false;
    if (hasInfo()) {
      if (!getInfo()
          .equals(other.getInfo())) return false;
    }
    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (subscriptionType_ != other.subscriptionType_) return false;
    if (getSelfRegistrationEnabled()
        != other.getSelfRegistrationEnabled()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInfo()) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SUBSCRIPTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + subscriptionType_;
    hash = (37 * hash) + SELF_REGISTRATION_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSelfRegistrationEnabled());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * For updating a tenant.
   * </pre>
   *
   * Protobuf type {@code account.tenant.v1.UpdateTenantRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.tenant.v1.UpdateTenantRequest)
      com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_UpdateTenantRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_UpdateTenantRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.class, com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.Builder.class);
    }

    // Construct using com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      id_ = "";
      name_ = "";
      subscriptionType_ = 0;
      selfRegistrationEnabled_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.vnworkday.proto.account.tenant.v1.TenantServiceProto.internal_static_account_tenant_v1_UpdateTenantRequest_descriptor;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest getDefaultInstanceForType() {
      return com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest build() {
      com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest buildPartial() {
      com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest result = new com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.info_ = infoBuilder_ == null
            ? info_
            : infoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.subscriptionType_ = subscriptionType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.selfRegistrationEnabled_ = selfRegistrationEnabled_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest) {
        return mergeFrom((com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest other) {
      if (other == com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest.getDefaultInstance()) return this;
      if (other.hasInfo()) {
        mergeInfo(other.getInfo());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.subscriptionType_ != 0) {
        setSubscriptionTypeValue(other.getSubscriptionTypeValue());
      }
      if (other.getSelfRegistrationEnabled() != false) {
        setSelfRegistrationEnabled(other.getSelfRegistrationEnabled());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              subscriptionType_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              selfRegistrationEnabled_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.vnworkday.proto.shared.v1.RequestInfo info_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.RequestInfo, com.github.vnworkday.proto.shared.v1.RequestInfo.Builder, com.github.vnworkday.proto.shared.v1.RequestInfoOrBuilder> infoBuilder_;
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     * @return The info.
     */
    public com.github.vnworkday.proto.shared.v1.RequestInfo getInfo() {
      if (infoBuilder_ == null) {
        return info_ == null ? com.github.vnworkday.proto.shared.v1.RequestInfo.getDefaultInstance() : info_;
      } else {
        return infoBuilder_.getMessage();
      }
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public Builder setInfo(com.github.vnworkday.proto.shared.v1.RequestInfo value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
      } else {
        infoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public Builder setInfo(
        com.github.vnworkday.proto.shared.v1.RequestInfo.Builder builderForValue) {
      if (infoBuilder_ == null) {
        info_ = builderForValue.build();
      } else {
        infoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public Builder mergeInfo(com.github.vnworkday.proto.shared.v1.RequestInfo value) {
      if (infoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          info_ != null &&
          info_ != com.github.vnworkday.proto.shared.v1.RequestInfo.getDefaultInstance()) {
          getInfoBuilder().mergeFrom(value);
        } else {
          info_ = value;
        }
      } else {
        infoBuilder_.mergeFrom(value);
      }
      if (info_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public Builder clearInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.RequestInfo.Builder getInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    public com.github.vnworkday.proto.shared.v1.RequestInfoOrBuilder getInfoOrBuilder() {
      if (infoBuilder_ != null) {
        return infoBuilder_.getMessageOrBuilder();
      } else {
        return info_ == null ?
            com.github.vnworkday.proto.shared.v1.RequestInfo.getDefaultInstance() : info_;
      }
    }
    /**
     * <code>.shared.v1.RequestInfo info = 1 [json_name = "info"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.vnworkday.proto.shared.v1.RequestInfo, com.github.vnworkday.proto.shared.v1.RequestInfo.Builder, com.github.vnworkday.proto.shared.v1.RequestInfoOrBuilder> 
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.vnworkday.proto.shared.v1.RequestInfo, com.github.vnworkday.proto.shared.v1.RequestInfo.Builder, com.github.vnworkday.proto.shared.v1.RequestInfoOrBuilder>(
                getInfo(),
                getParentForChildren(),
                isClean());
        info_ = null;
      }
      return infoBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Required. The ID of the tenant to update.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The ID of the tenant to update.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The ID of the tenant to update.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The ID of the tenant to update.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The ID of the tenant to update.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Required. The new name of the tenant. This must be unique across all tenants.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The new name of the tenant. This must be unique across all tenants.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The new name of the tenant. This must be unique across all tenants.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The new name of the tenant. This must be unique across all tenants.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The new name of the tenant. This must be unique across all tenants.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int subscriptionType_ = 0;
    /**
     * <pre>
     * Required. The new type of subscription for the tenant.
     * </pre>
     *
     * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
     * @return The enum numeric value on the wire for subscriptionType.
     */
    @java.lang.Override public int getSubscriptionTypeValue() {
      return subscriptionType_;
    }
    /**
     * <pre>
     * Required. The new type of subscription for the tenant.
     * </pre>
     *
     * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
     * @param value The enum numeric value on the wire for subscriptionType to set.
     * @return This builder for chaining.
     */
    public Builder setSubscriptionTypeValue(int value) {
      subscriptionType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The new type of subscription for the tenant.
     * </pre>
     *
     * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
     * @return The subscriptionType.
     */
    @java.lang.Override
    public com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType getSubscriptionType() {
      com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType result = com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.forNumber(subscriptionType_);
      return result == null ? com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Required. The new type of subscription for the tenant.
     * </pre>
     *
     * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
     * @param value The subscriptionType to set.
     * @return This builder for chaining.
     */
    public Builder setSubscriptionType(com.github.vnworkday.proto.account.tenant.v1.TenantSubscriptionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      subscriptionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The new type of subscription for the tenant.
     * </pre>
     *
     * <code>.account.tenant.v1.TenantSubscriptionType subscription_type = 4 [json_name = "subscriptionType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubscriptionType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      subscriptionType_ = 0;
      onChanged();
      return this;
    }

    private boolean selfRegistrationEnabled_ ;
    /**
     * <pre>
     * Optional. Whether self-registration is enabled for the tenant. Defaults to false if not set.
     * </pre>
     *
     * <code>bool self_registration_enabled = 5 [json_name = "selfRegistrationEnabled"];</code>
     * @return The selfRegistrationEnabled.
     */
    @java.lang.Override
    public boolean getSelfRegistrationEnabled() {
      return selfRegistrationEnabled_;
    }
    /**
     * <pre>
     * Optional. Whether self-registration is enabled for the tenant. Defaults to false if not set.
     * </pre>
     *
     * <code>bool self_registration_enabled = 5 [json_name = "selfRegistrationEnabled"];</code>
     * @param value The selfRegistrationEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setSelfRegistrationEnabled(boolean value) {

      selfRegistrationEnabled_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Whether self-registration is enabled for the tenant. Defaults to false if not set.
     * </pre>
     *
     * <code>bool self_registration_enabled = 5 [json_name = "selfRegistrationEnabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSelfRegistrationEnabled() {
      bitField0_ = (bitField0_ & ~0x00000010);
      selfRegistrationEnabled_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:account.tenant.v1.UpdateTenantRequest)
  }

  // @@protoc_insertion_point(class_scope:account.tenant.v1.UpdateTenantRequest)
  private static final com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest();
  }

  public static com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateTenantRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateTenantRequest>() {
    @java.lang.Override
    public UpdateTenantRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateTenantRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateTenantRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.vnworkday.proto.account.tenant.v1.UpdateTenantRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

