// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/tenant/v1/tenant_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.tenant.v1;

public interface UpdateTenantResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.tenant.v1.UpdateTenantResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  com.github.vnworkday.proto.shared.v1.Error getError();
  /**
   * <code>.shared.v1.Error error = 1 [json_name = "error"];</code>
   */
  com.github.vnworkday.proto.shared.v1.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * Required. The updated tenant.
   * </pre>
   *
   * <code>.account.tenant.v1.Tenant tenant = 2 [json_name = "tenant"];</code>
   * @return Whether the tenant field is set.
   */
  boolean hasTenant();
  /**
   * <pre>
   * Required. The updated tenant.
   * </pre>
   *
   * <code>.account.tenant.v1.Tenant tenant = 2 [json_name = "tenant"];</code>
   * @return The tenant.
   */
  com.github.vnworkday.proto.account.tenant.v1.Tenant getTenant();
  /**
   * <pre>
   * Required. The updated tenant.
   * </pre>
   *
   * <code>.account.tenant.v1.Tenant tenant = 2 [json_name = "tenant"];</code>
   */
  com.github.vnworkday.proto.account.tenant.v1.TenantOrBuilder getTenantOrBuilder();
}
