// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/user/v1/user_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.user.v1;

public interface CreateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.user.v1.CreateUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.account.user.v1.User user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.account.user.v1.User user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  com.github.vnworkday.proto.account.user.v1.User getUser();
  /**
   * <code>.account.user.v1.User user = 1 [json_name = "user"];</code>
   */
  com.github.vnworkday.proto.account.user.v1.UserOrBuilder getUserOrBuilder();
}
