// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account/user/v1/user_service.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.account.user.v1;

public interface DeleteUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.user.v1.DeleteUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
