// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/tracing.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

/**
 * <pre>
 * Entity type.
 * </pre>
 *
 * Protobuf enum {@code shared.v1.Entity}
 */
public enum Entity
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENTITY_UNSPECIFIED = 0;</code>
   */
  ENTITY_UNSPECIFIED(0),
  /**
   * <code>ENTITY_USER = 1;</code>
   */
  ENTITY_USER(1),
  /**
   * <code>ENTITY_SERVICE_ACCOUNT = 100;</code>
   */
  ENTITY_SERVICE_ACCOUNT(100),
  /**
   * <code>ENTITY_SERVICE_WORKFORCE = 101;</code>
   */
  ENTITY_SERVICE_WORKFORCE(101),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Entity.class.getName());
  }
  /**
   * <code>ENTITY_UNSPECIFIED = 0;</code>
   */
  public static final int ENTITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ENTITY_USER = 1;</code>
   */
  public static final int ENTITY_USER_VALUE = 1;
  /**
   * <code>ENTITY_SERVICE_ACCOUNT = 100;</code>
   */
  public static final int ENTITY_SERVICE_ACCOUNT_VALUE = 100;
  /**
   * <code>ENTITY_SERVICE_WORKFORCE = 101;</code>
   */
  public static final int ENTITY_SERVICE_WORKFORCE_VALUE = 101;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Entity valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Entity forNumber(int value) {
    switch (value) {
      case 0: return ENTITY_UNSPECIFIED;
      case 1: return ENTITY_USER;
      case 100: return ENTITY_SERVICE_ACCOUNT;
      case 101: return ENTITY_SERVICE_WORKFORCE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Entity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Entity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Entity>() {
          public Entity findValueByNumber(int number) {
            return Entity.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.vnworkday.proto.shared.v1.TracingProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Entity[] VALUES = values();

  public static Entity valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Entity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:shared.v1.Entity)
}

