// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/error.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

public final class ErrorProto {
  private ErrorProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ErrorProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shared_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shared_v1_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025shared/v1/error.proto\022\tshared.v1\"k\n\005Er" +
      "ror\022\022\n\004code\030\001 \001(\005R\004code\022\030\n\007message\030\002 \001(\t" +
      "R\007message\022\034\n\tretryable\030\003 \001(\010R\tretryable\022" +
      "\026\n\006reason\030\004 \001(\tR\006reasonBw\n$com.github.vn" +
      "workday.proto.shared.v1B\nErrorProtoP\001\242\002\003" +
      "SXX\252\002\tShared.V1\312\002\tShared\\V1\342\002\025Shared\\V1\\" +
      "GPBMetadata\352\002\nShared::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shared_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shared_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shared_v1_Error_descriptor,
        new java.lang.String[] { "Code", "Message", "Retryable", "Reason", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
