// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/tracing.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

public interface RequestInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shared.v1.RequestInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The correlation ID of the request for tracing purposes.
   * </pre>
   *
   * <code>string correlation_id = 1 [json_name = "correlationId"];</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <pre>
   * Required. The correlation ID of the request for tracing purposes.
   * </pre>
   *
   * <code>string correlation_id = 1 [json_name = "correlationId"];</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <pre>
   * Required. The owner, who initiated the chain of requests.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller owner = 2 [json_name = "owner"];</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <pre>
   * Required. The owner, who initiated the chain of requests.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller owner = 2 [json_name = "owner"];</code>
   * @return The owner.
   */
  com.github.vnworkday.proto.shared.v1.RequestCaller getOwner();
  /**
   * <pre>
   * Required. The owner, who initiated the chain of requests.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller owner = 2 [json_name = "owner"];</code>
   */
  com.github.vnworkday.proto.shared.v1.RequestCallerOrBuilder getOwnerOrBuilder();

  /**
   * <pre>
   * Required. The caller, who initiated the request.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller caller = 3 [json_name = "caller"];</code>
   * @return Whether the caller field is set.
   */
  boolean hasCaller();
  /**
   * <pre>
   * Required. The caller, who initiated the request.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller caller = 3 [json_name = "caller"];</code>
   * @return The caller.
   */
  com.github.vnworkday.proto.shared.v1.RequestCaller getCaller();
  /**
   * <pre>
   * Required. The caller, who initiated the request.
   * </pre>
   *
   * <code>.shared.v1.RequestCaller caller = 3 [json_name = "caller"];</code>
   */
  com.github.vnworkday.proto.shared.v1.RequestCallerOrBuilder getCallerOrBuilder();

  /**
   * <pre>
   * Optional. The IP address of the original client who initiated the request.
   * </pre>
   *
   * <code>string ip_address = 4 [json_name = "ipAddress"];</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <pre>
   * Optional. The IP address of the original client who initiated the request.
   * </pre>
   *
   * <code>string ip_address = 4 [json_name = "ipAddress"];</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <pre>
   * Required. The service that initiated the request.
   * </pre>
   *
   * <code>string owner_service = 5 [json_name = "ownerService"];</code>
   * @return The ownerService.
   */
  java.lang.String getOwnerService();
  /**
   * <pre>
   * Required. The service that initiated the request.
   * </pre>
   *
   * <code>string owner_service = 5 [json_name = "ownerService"];</code>
   * @return The bytes for ownerService.
   */
  com.google.protobuf.ByteString
      getOwnerServiceBytes();

  /**
   * <pre>
   * Required. The service that acts as the caller of the request.
   * </pre>
   *
   * <code>string caller_service = 6 [json_name = "callerService"];</code>
   * @return The callerService.
   */
  java.lang.String getCallerService();
  /**
   * <pre>
   * Required. The service that acts as the caller of the request.
   * </pre>
   *
   * <code>string caller_service = 6 [json_name = "callerService"];</code>
   * @return The bytes for callerService.
   */
  com.google.protobuf.ByteString
      getCallerServiceBytes();
}
