// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/request.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

/**
 * Protobuf type {@code shared.v1.RequestFilter}
 */
public final class RequestFilter extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shared.v1.RequestFilter)
    RequestFilterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      RequestFilter.class.getName());
  }
  // Use RequestFilter.newBuilder() to construct.
  private RequestFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestFilter() {
    field_ = "";
    value_ = "";
    operator_ = 0;
    valueType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.vnworkday.proto.shared.v1.RequestProto.internal_static_shared_v1_RequestFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.vnworkday.proto.shared.v1.RequestProto.internal_static_shared_v1_RequestFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.vnworkday.proto.shared.v1.RequestFilter.class, com.github.vnworkday.proto.shared.v1.RequestFilter.Builder.class);
  }

  public static final int FIELD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object field_ = "";
  /**
   * <pre>
   * Required. The field to filter by.
   * </pre>
   *
   * <code>string field = 1 [json_name = "field"];</code>
   * @return The field.
   */
  @java.lang.Override
  public java.lang.String getField() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The field to filter by.
   * </pre>
   *
   * <code>string field = 1 [json_name = "field"];</code>
   * @return The bytes for field.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFieldBytes() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object value_ = "";
  /**
   * <pre>
   * Conditionally required. The value to filter by.
   * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
   * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
   * </pre>
   *
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Conditionally required. The value to filter by.
   * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
   * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
   * </pre>
   *
   * <code>string value = 2 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATOR_FIELD_NUMBER = 3;
  private int operator_ = 0;
  /**
   * <pre>
   * Required. The operator to use for the filter.
   * </pre>
   *
   * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
   * @return The enum numeric value on the wire for operator.
   */
  @java.lang.Override public int getOperatorValue() {
    return operator_;
  }
  /**
   * <pre>
   * Required. The operator to use for the filter.
   * </pre>
   *
   * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
   * @return The operator.
   */
  @java.lang.Override public com.github.vnworkday.proto.shared.v1.Operator getOperator() {
    com.github.vnworkday.proto.shared.v1.Operator result = com.github.vnworkday.proto.shared.v1.Operator.forNumber(operator_);
    return result == null ? com.github.vnworkday.proto.shared.v1.Operator.UNRECOGNIZED : result;
  }

  public static final int IS_CASE_SENSITIVE_FIELD_NUMBER = 4;
  private boolean isCaseSensitive_ = false;
  /**
   * <pre>
   * Optional. Whether the filter is case sensitive. The default is false.
   * </pre>
   *
   * <code>bool is_case_sensitive = 4 [json_name = "isCaseSensitive"];</code>
   * @return The isCaseSensitive.
   */
  @java.lang.Override
  public boolean getIsCaseSensitive() {
    return isCaseSensitive_;
  }

  public static final int VALUE_TYPE_FIELD_NUMBER = 5;
  private int valueType_ = 0;
  /**
   * <pre>
   * Optional. The type of the value. The default is string.
   * </pre>
   *
   * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
   * @return The enum numeric value on the wire for valueType.
   */
  @java.lang.Override public int getValueTypeValue() {
    return valueType_;
  }
  /**
   * <pre>
   * Optional. The type of the value. The default is string.
   * </pre>
   *
   * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
   * @return The valueType.
   */
  @java.lang.Override public com.github.vnworkday.proto.shared.v1.ValueType getValueType() {
    com.github.vnworkday.proto.shared.v1.ValueType result = com.github.vnworkday.proto.shared.v1.ValueType.forNumber(valueType_);
    return result == null ? com.github.vnworkday.proto.shared.v1.ValueType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(field_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, field_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
    }
    if (operator_ != com.github.vnworkday.proto.shared.v1.Operator.OPERATOR_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, operator_);
    }
    if (isCaseSensitive_ != false) {
      output.writeBool(4, isCaseSensitive_);
    }
    if (valueType_ != com.github.vnworkday.proto.shared.v1.ValueType.VALUE_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, valueType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(field_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, field_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
    }
    if (operator_ != com.github.vnworkday.proto.shared.v1.Operator.OPERATOR_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, operator_);
    }
    if (isCaseSensitive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isCaseSensitive_);
    }
    if (valueType_ != com.github.vnworkday.proto.shared.v1.ValueType.VALUE_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, valueType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.vnworkday.proto.shared.v1.RequestFilter)) {
      return super.equals(obj);
    }
    com.github.vnworkday.proto.shared.v1.RequestFilter other = (com.github.vnworkday.proto.shared.v1.RequestFilter) obj;

    if (!getField()
        .equals(other.getField())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (operator_ != other.operator_) return false;
    if (getIsCaseSensitive()
        != other.getIsCaseSensitive()) return false;
    if (valueType_ != other.valueType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIELD_FIELD_NUMBER;
    hash = (53 * hash) + getField().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + operator_;
    hash = (37 * hash) + IS_CASE_SENSITIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCaseSensitive());
    hash = (37 * hash) + VALUE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + valueType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.shared.v1.RequestFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.vnworkday.proto.shared.v1.RequestFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shared.v1.RequestFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shared.v1.RequestFilter)
      com.github.vnworkday.proto.shared.v1.RequestFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vnworkday.proto.shared.v1.RequestProto.internal_static_shared_v1_RequestFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vnworkday.proto.shared.v1.RequestProto.internal_static_shared_v1_RequestFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vnworkday.proto.shared.v1.RequestFilter.class, com.github.vnworkday.proto.shared.v1.RequestFilter.Builder.class);
    }

    // Construct using com.github.vnworkday.proto.shared.v1.RequestFilter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      field_ = "";
      value_ = "";
      operator_ = 0;
      isCaseSensitive_ = false;
      valueType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.vnworkday.proto.shared.v1.RequestProto.internal_static_shared_v1_RequestFilter_descriptor;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.RequestFilter getDefaultInstanceForType() {
      return com.github.vnworkday.proto.shared.v1.RequestFilter.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.RequestFilter build() {
      com.github.vnworkday.proto.shared.v1.RequestFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.RequestFilter buildPartial() {
      com.github.vnworkday.proto.shared.v1.RequestFilter result = new com.github.vnworkday.proto.shared.v1.RequestFilter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.vnworkday.proto.shared.v1.RequestFilter result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.field_ = field_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.operator_ = operator_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isCaseSensitive_ = isCaseSensitive_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.valueType_ = valueType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.vnworkday.proto.shared.v1.RequestFilter) {
        return mergeFrom((com.github.vnworkday.proto.shared.v1.RequestFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.vnworkday.proto.shared.v1.RequestFilter other) {
      if (other == com.github.vnworkday.proto.shared.v1.RequestFilter.getDefaultInstance()) return this;
      if (!other.getField().isEmpty()) {
        field_ = other.field_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.operator_ != 0) {
        setOperatorValue(other.getOperatorValue());
      }
      if (other.getIsCaseSensitive() != false) {
        setIsCaseSensitive(other.getIsCaseSensitive());
      }
      if (other.valueType_ != 0) {
        setValueTypeValue(other.getValueTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              field_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              value_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              operator_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isCaseSensitive_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              valueType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object field_ = "";
    /**
     * <pre>
     * Required. The field to filter by.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The field.
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The field to filter by.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return The bytes for field.
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The field to filter by.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The field to set.
     * @return This builder for chaining.
     */
    public Builder setField(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      field_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The field to filter by.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @return This builder for chaining.
     */
    public Builder clearField() {
      field_ = getDefaultInstance().getField();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The field to filter by.
     * </pre>
     *
     * <code>string field = 1 [json_name = "field"];</code>
     * @param value The bytes for field to set.
     * @return This builder for chaining.
     */
    public Builder setFieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      field_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <pre>
     * Conditionally required. The value to filter by.
     * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
     * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
     * </pre>
     *
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Conditionally required. The value to filter by.
     * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
     * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
     * </pre>
     *
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Conditionally required. The value to filter by.
     * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
     * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
     * </pre>
     *
     * <code>string value = 2 [json_name = "value"];</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Conditionally required. The value to filter by.
     * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
     * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
     * </pre>
     *
     * <code>string value = 2 [json_name = "value"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      value_ = getDefaultInstance().getValue();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Conditionally required. The value to filter by.
     * If the operator is 'null' or 'not_null', the value will be ignored and can be omitted.
     * If the operator is 'in' or 'not_in', the value should be a list of values separated by vertical bars '|'.
     * </pre>
     *
     * <code>string value = 2 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int operator_ = 0;
    /**
     * <pre>
     * Required. The operator to use for the filter.
     * </pre>
     *
     * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
     * @return The enum numeric value on the wire for operator.
     */
    @java.lang.Override public int getOperatorValue() {
      return operator_;
    }
    /**
     * <pre>
     * Required. The operator to use for the filter.
     * </pre>
     *
     * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
     * @param value The enum numeric value on the wire for operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorValue(int value) {
      operator_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The operator to use for the filter.
     * </pre>
     *
     * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
     * @return The operator.
     */
    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.Operator getOperator() {
      com.github.vnworkday.proto.shared.v1.Operator result = com.github.vnworkday.proto.shared.v1.Operator.forNumber(operator_);
      return result == null ? com.github.vnworkday.proto.shared.v1.Operator.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Required. The operator to use for the filter.
     * </pre>
     *
     * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
     * @param value The operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperator(com.github.vnworkday.proto.shared.v1.Operator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      operator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The operator to use for the filter.
     * </pre>
     *
     * <code>.shared.v1.Operator operator = 3 [json_name = "operator"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOperator() {
      bitField0_ = (bitField0_ & ~0x00000004);
      operator_ = 0;
      onChanged();
      return this;
    }

    private boolean isCaseSensitive_ ;
    /**
     * <pre>
     * Optional. Whether the filter is case sensitive. The default is false.
     * </pre>
     *
     * <code>bool is_case_sensitive = 4 [json_name = "isCaseSensitive"];</code>
     * @return The isCaseSensitive.
     */
    @java.lang.Override
    public boolean getIsCaseSensitive() {
      return isCaseSensitive_;
    }
    /**
     * <pre>
     * Optional. Whether the filter is case sensitive. The default is false.
     * </pre>
     *
     * <code>bool is_case_sensitive = 4 [json_name = "isCaseSensitive"];</code>
     * @param value The isCaseSensitive to set.
     * @return This builder for chaining.
     */
    public Builder setIsCaseSensitive(boolean value) {

      isCaseSensitive_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Whether the filter is case sensitive. The default is false.
     * </pre>
     *
     * <code>bool is_case_sensitive = 4 [json_name = "isCaseSensitive"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCaseSensitive() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isCaseSensitive_ = false;
      onChanged();
      return this;
    }

    private int valueType_ = 0;
    /**
     * <pre>
     * Optional. The type of the value. The default is string.
     * </pre>
     *
     * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
     * @return The enum numeric value on the wire for valueType.
     */
    @java.lang.Override public int getValueTypeValue() {
      return valueType_;
    }
    /**
     * <pre>
     * Optional. The type of the value. The default is string.
     * </pre>
     *
     * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
     * @param value The enum numeric value on the wire for valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueTypeValue(int value) {
      valueType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The type of the value. The default is string.
     * </pre>
     *
     * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
     * @return The valueType.
     */
    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.ValueType getValueType() {
      com.github.vnworkday.proto.shared.v1.ValueType result = com.github.vnworkday.proto.shared.v1.ValueType.forNumber(valueType_);
      return result == null ? com.github.vnworkday.proto.shared.v1.ValueType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional. The type of the value. The default is string.
     * </pre>
     *
     * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
     * @param value The valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueType(com.github.vnworkday.proto.shared.v1.ValueType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      valueType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The type of the value. The default is string.
     * </pre>
     *
     * <code>.shared.v1.ValueType value_type = 5 [json_name = "valueType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValueType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      valueType_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shared.v1.RequestFilter)
  }

  // @@protoc_insertion_point(class_scope:shared.v1.RequestFilter)
  private static final com.github.vnworkday.proto.shared.v1.RequestFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.vnworkday.proto.shared.v1.RequestFilter();
  }

  public static com.github.vnworkday.proto.shared.v1.RequestFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestFilter>
      PARSER = new com.google.protobuf.AbstractParser<RequestFilter>() {
    @java.lang.Override
    public RequestFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.RequestFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

