// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/response.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

public interface ResponsePaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shared.v1.ResponsePagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
   * </pre>
   *
   * <code>string next_token = 1 [json_name = "nextToken"];</code>
   * @return The nextToken.
   */
  java.lang.String getNextToken();
  /**
   * <pre>
   * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
   * </pre>
   *
   * <code>string next_token = 1 [json_name = "nextToken"];</code>
   * @return The bytes for nextToken.
   */
  com.google.protobuf.ByteString
      getNextTokenBytes();

  /**
   * <pre>
   * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
   * </pre>
   *
   * <code>string previous_token = 2 [json_name = "previousToken"];</code>
   * @return The previousToken.
   */
  java.lang.String getPreviousToken();
  /**
   * <pre>
   * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
   * </pre>
   *
   * <code>string previous_token = 2 [json_name = "previousToken"];</code>
   * @return The bytes for previousToken.
   */
  com.google.protobuf.ByteString
      getPreviousTokenBytes();

  /**
   * <pre>
   * Required. The total number of items.
   * </pre>
   *
   * <code>int32 total = 3 [json_name = "total"];</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <pre>
   * Required. The total number of pages.
   * </pre>
   *
   * <code>int32 total_pages = 4 [json_name = "totalPages"];</code>
   * @return The totalPages.
   */
  int getTotalPages();
}
