// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/response.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

/**
 * Protobuf type {@code shared.v1.ResponsePagination}
 */
public final class ResponsePagination extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shared.v1.ResponsePagination)
    ResponsePaginationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ResponsePagination.class.getName());
  }
  // Use ResponsePagination.newBuilder() to construct.
  private ResponsePagination(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponsePagination() {
    nextToken_ = "";
    previousToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.vnworkday.proto.shared.v1.ResponseProto.internal_static_shared_v1_ResponsePagination_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.vnworkday.proto.shared.v1.ResponseProto.internal_static_shared_v1_ResponsePagination_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.vnworkday.proto.shared.v1.ResponsePagination.class, com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder.class);
  }

  public static final int NEXT_TOKEN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextToken_ = "";
  /**
   * <pre>
   * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
   * </pre>
   *
   * <code>string next_token = 1 [json_name = "nextToken"];</code>
   * @return The nextToken.
   */
  @java.lang.Override
  public java.lang.String getNextToken() {
    java.lang.Object ref = nextToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
   * </pre>
   *
   * <code>string next_token = 1 [json_name = "nextToken"];</code>
   * @return The bytes for nextToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextTokenBytes() {
    java.lang.Object ref = nextToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREVIOUS_TOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object previousToken_ = "";
  /**
   * <pre>
   * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
   * </pre>
   *
   * <code>string previous_token = 2 [json_name = "previousToken"];</code>
   * @return The previousToken.
   */
  @java.lang.Override
  public java.lang.String getPreviousToken() {
    java.lang.Object ref = previousToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      previousToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
   * </pre>
   *
   * <code>string previous_token = 2 [json_name = "previousToken"];</code>
   * @return The bytes for previousToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPreviousTokenBytes() {
    java.lang.Object ref = previousToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      previousToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 3;
  private int total_ = 0;
  /**
   * <pre>
   * Required. The total number of items.
   * </pre>
   *
   * <code>int32 total = 3 [json_name = "total"];</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  public static final int TOTAL_PAGES_FIELD_NUMBER = 4;
  private int totalPages_ = 0;
  /**
   * <pre>
   * Required. The total number of pages.
   * </pre>
   *
   * <code>int32 total_pages = 4 [json_name = "totalPages"];</code>
   * @return The totalPages.
   */
  @java.lang.Override
  public int getTotalPages() {
    return totalPages_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, nextToken_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(previousToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, previousToken_);
    }
    if (total_ != 0) {
      output.writeInt32(3, total_);
    }
    if (totalPages_ != 0) {
      output.writeInt32(4, totalPages_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nextToken_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(previousToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, previousToken_);
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, total_);
    }
    if (totalPages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalPages_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.vnworkday.proto.shared.v1.ResponsePagination)) {
      return super.equals(obj);
    }
    com.github.vnworkday.proto.shared.v1.ResponsePagination other = (com.github.vnworkday.proto.shared.v1.ResponsePagination) obj;

    if (!getNextToken()
        .equals(other.getNextToken())) return false;
    if (!getPreviousToken()
        .equals(other.getPreviousToken())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (getTotalPages()
        != other.getTotalPages()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NEXT_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextToken().hashCode();
    hash = (37 * hash) + PREVIOUS_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getPreviousToken().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPages();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.vnworkday.proto.shared.v1.ResponsePagination parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.vnworkday.proto.shared.v1.ResponsePagination prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shared.v1.ResponsePagination}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shared.v1.ResponsePagination)
      com.github.vnworkday.proto.shared.v1.ResponsePaginationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vnworkday.proto.shared.v1.ResponseProto.internal_static_shared_v1_ResponsePagination_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vnworkday.proto.shared.v1.ResponseProto.internal_static_shared_v1_ResponsePagination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vnworkday.proto.shared.v1.ResponsePagination.class, com.github.vnworkday.proto.shared.v1.ResponsePagination.Builder.class);
    }

    // Construct using com.github.vnworkday.proto.shared.v1.ResponsePagination.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nextToken_ = "";
      previousToken_ = "";
      total_ = 0;
      totalPages_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.vnworkday.proto.shared.v1.ResponseProto.internal_static_shared_v1_ResponsePagination_descriptor;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.ResponsePagination getDefaultInstanceForType() {
      return com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.ResponsePagination build() {
      com.github.vnworkday.proto.shared.v1.ResponsePagination result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.vnworkday.proto.shared.v1.ResponsePagination buildPartial() {
      com.github.vnworkday.proto.shared.v1.ResponsePagination result = new com.github.vnworkday.proto.shared.v1.ResponsePagination(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.vnworkday.proto.shared.v1.ResponsePagination result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nextToken_ = nextToken_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.previousToken_ = previousToken_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.total_ = total_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalPages_ = totalPages_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.vnworkday.proto.shared.v1.ResponsePagination) {
        return mergeFrom((com.github.vnworkday.proto.shared.v1.ResponsePagination)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.vnworkday.proto.shared.v1.ResponsePagination other) {
      if (other == com.github.vnworkday.proto.shared.v1.ResponsePagination.getDefaultInstance()) return this;
      if (!other.getNextToken().isEmpty()) {
        nextToken_ = other.nextToken_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPreviousToken().isEmpty()) {
        previousToken_ = other.previousToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      if (other.getTotalPages() != 0) {
        setTotalPages(other.getTotalPages());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              nextToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              previousToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalPages_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object nextToken_ = "";
    /**
     * <pre>
     * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
     * </pre>
     *
     * <code>string next_token = 1 [json_name = "nextToken"];</code>
     * @return The nextToken.
     */
    public java.lang.String getNextToken() {
      java.lang.Object ref = nextToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
     * </pre>
     *
     * <code>string next_token = 1 [json_name = "nextToken"];</code>
     * @return The bytes for nextToken.
     */
    public com.google.protobuf.ByteString
        getNextTokenBytes() {
      java.lang.Object ref = nextToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
     * </pre>
     *
     * <code>string next_token = 1 [json_name = "nextToken"];</code>
     * @param value The nextToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
     * </pre>
     *
     * <code>string next_token = 1 [json_name = "nextToken"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextToken() {
      nextToken_ = getDefaultInstance().getNextToken();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the next page. If the token is empty, it means that there are no more pages.
     * </pre>
     *
     * <code>string next_token = 1 [json_name = "nextToken"];</code>
     * @param value The bytes for nextToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nextToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object previousToken_ = "";
    /**
     * <pre>
     * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
     * </pre>
     *
     * <code>string previous_token = 2 [json_name = "previousToken"];</code>
     * @return The previousToken.
     */
    public java.lang.String getPreviousToken() {
      java.lang.Object ref = previousToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        previousToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
     * </pre>
     *
     * <code>string previous_token = 2 [json_name = "previousToken"];</code>
     * @return The bytes for previousToken.
     */
    public com.google.protobuf.ByteString
        getPreviousTokenBytes() {
      java.lang.Object ref = previousToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        previousToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
     * </pre>
     *
     * <code>string previous_token = 2 [json_name = "previousToken"];</code>
     * @param value The previousToken to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      previousToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
     * </pre>
     *
     * <code>string previous_token = 2 [json_name = "previousToken"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPreviousToken() {
      previousToken_ = getDefaultInstance().getPreviousToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The token that can be used to fetch the previous page. If the token is empty, it means that there are no previous pages.
     * </pre>
     *
     * <code>string previous_token = 2 [json_name = "previousToken"];</code>
     * @param value The bytes for previousToken to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      previousToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int total_ ;
    /**
     * <pre>
     * Required. The total number of items.
     * </pre>
     *
     * <code>int32 total = 3 [json_name = "total"];</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <pre>
     * Required. The total number of items.
     * </pre>
     *
     * <code>int32 total = 3 [json_name = "total"];</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The total number of items.
     * </pre>
     *
     * <code>int32 total = 3 [json_name = "total"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000004);
      total_ = 0;
      onChanged();
      return this;
    }

    private int totalPages_ ;
    /**
     * <pre>
     * Required. The total number of pages.
     * </pre>
     *
     * <code>int32 total_pages = 4 [json_name = "totalPages"];</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }
    /**
     * <pre>
     * Required. The total number of pages.
     * </pre>
     *
     * <code>int32 total_pages = 4 [json_name = "totalPages"];</code>
     * @param value The totalPages to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPages(int value) {

      totalPages_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The total number of pages.
     * </pre>
     *
     * <code>int32 total_pages = 4 [json_name = "totalPages"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPages() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalPages_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shared.v1.ResponsePagination)
  }

  // @@protoc_insertion_point(class_scope:shared.v1.ResponsePagination)
  private static final com.github.vnworkday.proto.shared.v1.ResponsePagination DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.vnworkday.proto.shared.v1.ResponsePagination();
  }

  public static com.github.vnworkday.proto.shared.v1.ResponsePagination getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponsePagination>
      PARSER = new com.google.protobuf.AbstractParser<ResponsePagination>() {
    @java.lang.Override
    public ResponsePagination parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResponsePagination> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponsePagination> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.vnworkday.proto.shared.v1.ResponsePagination getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

