// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/v1/response.proto
// Protobuf Java Version: 4.27.0

package com.github.vnworkday.proto.shared.v1;

public final class ResponseProto {
  private ResponseProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ResponseProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shared_v1_ResponsePagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shared_v1_ResponsePagination_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030shared/v1/response.proto\022\tshared.v1\"\221\001" +
      "\n\022ResponsePagination\022\035\n\nnext_token\030\001 \001(\t" +
      "R\tnextToken\022%\n\016previous_token\030\002 \001(\tR\rpre" +
      "viousToken\022\024\n\005total\030\003 \001(\005R\005total\022\037\n\013tota" +
      "l_pages\030\004 \001(\005R\ntotalPagesBz\n$com.github." +
      "vnworkday.proto.shared.v1B\rResponseProto" +
      "P\001\242\002\003SXX\252\002\tShared.V1\312\002\tShared\\V1\342\002\025Share" +
      "d\\V1\\GPBMetadata\352\002\nShared::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shared_v1_ResponsePagination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shared_v1_ResponsePagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shared_v1_ResponsePagination_descriptor,
        new java.lang.String[] { "NextToken", "PreviousToken", "Total", "TotalPages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
