name: pull-request
run-name: Pull Request Lint by ${{ github.actor }}
on:
  # Trigger the workflow on pull request to main, staging, and production branches
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Buf Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
      - name: Run Buf Breaking
        uses: bufbuild/buf-breaking-action@v1
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        # Only run buf breaking if the PR title does not contain 'BREAKING'
        if: contains(env.PR_TITLE, 'BREAKING') == false
        with:
          against: "https://github.com/vnworkday/proto.git#branch=main,subdir=proto"
          input: proto